name: Mecaron
favicon: null
layout_spectrum: 0.06062800018116832
typography_spectrum: 0.027900678338482976
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#532d00'
    - '#e1d1c1'
    - '#c6a242'
    - '#a07612'
  brandStrength: 0.6875
  lightness: 0.3592163883149624
  saturation: 0.9894219639245421
  rhythmicContrast: 0.5963970308657736
purpose: []
